#!/bin/bash
# Helper script to start API capture session

echo "=========================================="
echo "Ambient One API Capture Tool"
echo "=========================================="
echo ""
echo "This script will help you capture the Ambient Works API traffic."
echo ""
echo "📋 Before starting, make sure you:"
echo "   1. Have Firefox installed"
echo "   2. Know your Ambient Works login credentials"
echo ""
echo "🚀 Starting mitmweb..."
echo ""
echo "Next steps (after mitmweb starts):"
echo "   1. Configure Firefox proxy:"
echo "      Settings → Network → Manual proxy: 127.0.0.1:8080"
echo ""
echo "   2. Install certificate:"
echo "      Visit http://mitm.it → Download macOS cert"
echo "      Add to System keychain → Trust it"
echo ""
echo "   3. Visit https://app.ambientworks.io/"
echo "      Log in and navigate around"
echo ""
echo "   4. Export capture:"
echo "      File → Save as .har format"
echo ""
echo "   5. Analyze:"
echo "      python scripts/analyze_capture.py <file.har>"
echo ""
echo "=========================================="
echo ""
echo "Press Ctrl+C to stop mitmweb when done"
echo ""

# Start mitmweb
mitmweb --set console_eventlog_verbosity=error
